### ISSUE TITLE
uninitialized constant Fastlane::Actions::RepackIosAction::Match

### ISSUE THREAD

**Issue by chriswilke** [creaworks-labs/fastlane-plugin-repack-ios#2]
I receive the following error when trying to use repack-ios to replace an Assets.car file and resign the .ipa.

NameError: [!] uninitialized constant Fastlane::Actions::RepackIosAction::Match
Did you mean?  Math

**FASTLANE FILE**
`lane :test_repack do
  if ENV['SCHEME'] != nil
  
    cert(
        output_path: ("./fastlane/certs")
    )
    sigh(
        output_path: ("./fastlane/certs")
    )

    repack_ios({
      ipa: "./fastlane/builds/#{ENV['SCHEME']}.ipa",
      contents: "./fastlane/builds/test2/"
    })
  else
    execute_for_UPDATE_envs{ test_repack }
  end
end
`

**Comment by omerduzyol** [comment]
@chriswilke Would you be able to share your fastlane & ruby versions?

**Comment by omerduzyol** [comment]
We've identified the issue and a new version is on the way. Thanks for sharing this.

**Comment by chriswilke** [comment]
Thanks.  Sorry about my delayed response, September became very busy.  

All the best.
